# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#05070A"

# Main text color
theme[main_fg]="#E1E8EC"

# Title color for boxes
theme[title]="#E1E8EC"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7FB5E5"

# Background color of selected item in processes box
theme[selected_bg]="#223246"

# Foreground color of selected item in processes box
theme[selected_fg]="#E1E8EC"

# Color of inactive/disabled text
theme[inactive_fg]="#7D8992"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#B8C3CA"

# Background color of the percentage meters
theme[meter_bg]="#1B232B"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#B8C3CA"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#A9CCE8" # Ice
theme[mem_box]="#6F9FD0" # Distant blue
theme[net_box]="#78BBC4" # Cyan
theme[proc_box]="#7FB5E5" # Blue

# Box divider line and small boxes line color
theme[div_line]="#3A4652"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9CB68E"
theme[temp_mid]="#D3B26F"
theme[temp_end]="#D9858B"

# CPU graph colors (Cyan -> Ice)
theme[cpu_start]="#78BBC4"
theme[cpu_mid]="#6F9FD0"
theme[cpu_end]="#A9CCE8"

# Mem/Disk free meter (Distant blue -> Blue -> Ice)
theme[free_start]="#6F9FD0"
theme[free_mid]="#7FB5E5"
theme[free_end]="#A9CCE8"

# Mem/Disk cached meter (Muted -> Distant blue -> Blue)
theme[cached_start]="#7D8992"
theme[cached_mid]="#6F9FD0"
theme[cached_end]="#7FB5E5"

# Mem/Disk available meter (Green -> Cyan -> Ice)
theme[available_start]="#9CB68E"
theme[available_mid]="#78BBC4"
theme[available_end]="#A9CCE8"

# Mem/Disk used meter (Green -> Warning -> Error)
theme[used_start]="#9CB68E"
theme[used_mid]="#D3B26F"
theme[used_end]="#D9858B"

# Download graph colors (Distant blue -> Blue -> Ice)
theme[download_start]="#6F9FD0"
theme[download_mid]="#7FB5E5"
theme[download_end]="#A9CCE8"

# Upload graph colors (Green -> Cyan -> Ice)
theme[upload_start]="#9CB68E"
theme[upload_mid]="#78BBC4"
theme[upload_end]="#A9CCE8"

# Process box color gradient for threads, mem and cpu usage (Muted -> Distant blue -> Blue)
theme[process_start]="#7D8992"
theme[process_mid]="#6F9FD0"
theme[process_end]="#7FB5E5"
