# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#05070A"

# Main text color
theme[main_fg]="#E1E8EC"

# Title color for boxes
theme[title]="#E1E8EC"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7FB5E5"

# Background color of selected item in processes box
theme[selected_bg]="#223246"

# Foreground color of selected item in processes box
theme[selected_fg]="#A9CCE8"

# Color of inactive/disabled text
theme[inactive_fg]="#7D8992"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#B8C3CA"

# Background color of the percentage meters
theme[meter_bg]="#1B232B"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#B8C3CA"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#B3A1D6" # Violet
theme[mem_box]="#9CB68E" # Green
theme[net_box]="#D9858B" # Error
theme[proc_box]="#7FB5E5" # Blue

# Box divider line and small boxes line color
theme[div_line]="#3A4652"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9CB68E"
theme[temp_mid]="#D3B26F"
theme[temp_end]="#D9858B"

# CPU graph colors (Cyan -> Ice)
theme[cpu_start]="#78BBC4"
theme[cpu_mid]="#6F9FD0"
theme[cpu_end]="#A9CCE8"

# Mem/Disk free meter (Violet -> Ice -> Blue)
theme[free_start]="#B3A1D6"
theme[free_mid]="#A9CCE8"
theme[free_end]="#7FB5E5"

# Mem/Disk cached meter (Distant blue -> Ice)
theme[cached_start]="#6F9FD0"
theme[cached_mid]="#7FB5E5"
theme[cached_end]="#A9CCE8"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#D0A17E"
theme[available_mid]="#D3B26F"
theme[available_end]="#D9858B"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#9CB68E"
theme[used_mid]="#78BBC4"
theme[used_end]="#A9CCE8"

# Download graph colors (Peach -> Red)
theme[download_start]="#D0A17E"
theme[download_mid]="#D3B26F"
theme[download_end]="#D9858B"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#9CB68E"
theme[upload_mid]="#78BBC4"
theme[upload_end]="#A9CCE8"

# Process box color gradient for threads, mem and cpu usage (Distant blue -> Violet)
theme[process_start]="#6F9FD0"
theme[process_mid]="#A9CCE8"
theme[process_end]="#B3A1D6"
