local colors = {
	base = "#05070A",
	deep = "#0A0D11",
	surface = "#13181E",
	raised = "#1B232B",
	selection = "#223246",
	border = "#3A4652",
	text = "#E1E8EC",
	secondary = "#B8C3CA",
	muted = "#7D8992",
	distant_blue = "#6F9FD0",
	blue = "#7FB5E5",
	ice = "#A9CCE8",
	cyan = "#78BBC4",
	green = "#9CB68E",
	violet = "#B3A1D6",
	peach = "#D0A17E",
	warning = "#D3B26F",
	error = "#D9858B",
}

local groups = {
	Normal = { fg = colors.text, bg = "NONE" },
	NormalNC = { fg = colors.secondary, bg = "NONE" },
	NormalFloat = { fg = colors.text, bg = colors.surface },
	FloatBorder = { fg = colors.border, bg = colors.surface },
	FloatTitle = { fg = colors.ice, bg = colors.surface, bold = true },
	EndOfBuffer = { fg = colors.base, bg = "NONE" },
	SignColumn = { fg = colors.muted, bg = "NONE" },
	FoldColumn = { fg = colors.muted, bg = "NONE" },
	Folded = { fg = colors.secondary, bg = colors.deep },
	Cursor = { fg = colors.base, bg = colors.ice },
	lCursor = { link = "Cursor" },
	CursorIM = { link = "Cursor" },
	TermCursor = { link = "Cursor" },
	CursorLine = { bg = colors.deep },
	CursorColumn = { bg = colors.deep },
	ColorColumn = { bg = colors.surface },
	LineNr = { fg = colors.muted },
	CursorLineNr = { fg = colors.ice, bold = true },
	CursorLineSign = { bg = colors.deep },
	CursorLineFold = { bg = colors.deep },
	Visual = { fg = colors.text, bg = colors.selection },
	VisualNOS = { link = "Visual" },
	Search = { fg = colors.text, bg = colors.selection },
	IncSearch = { fg = colors.base, bg = colors.ice, bold = true },
	CurSearch = { link = "IncSearch" },
	Substitute = { fg = colors.base, bg = colors.blue },
	MatchParen = { fg = colors.ice, bg = colors.selection, bold = true },
	Whitespace = { fg = colors.raised },
	NonText = { fg = colors.border },
	SpecialKey = { fg = colors.border },
	Conceal = { fg = colors.muted },
	Directory = { fg = colors.blue },
	Title = { fg = colors.ice, bold = true },
	Question = { fg = colors.green },
	MoreMsg = { fg = colors.blue },
	ModeMsg = { fg = colors.secondary, bold = true },
	ErrorMsg = { fg = colors.error },
	WarningMsg = { fg = colors.warning },
	OkMsg = { fg = colors.green },
	MsgArea = { fg = colors.secondary },
	QuickFixLine = { fg = colors.text, bg = colors.selection },
	qfLineNr = { fg = colors.ice },
	WinSeparator = { fg = colors.border },
	StatusLine = { fg = colors.secondary, bg = colors.raised },
	StatusLineNC = { fg = colors.muted, bg = colors.deep },
	WinBar = { fg = colors.secondary, bg = "NONE" },
	WinBarNC = { fg = colors.muted, bg = "NONE" },
	TabLine = { fg = colors.muted, bg = colors.deep },
	TabLineFill = { bg = colors.base },
	TabLineSel = { fg = colors.text, bg = colors.selection, bold = true },
	WildMenu = { fg = colors.text, bg = colors.selection },
	Pmenu = { fg = colors.muted, bg = colors.surface },
	PmenuSel = { fg = colors.text, bg = colors.selection, bold = true },
	PmenuKind = { fg = colors.cyan, bg = colors.surface },
	PmenuKindSel = { fg = colors.text, bg = colors.selection, bold = true },
	PmenuExtra = { fg = colors.secondary, bg = colors.surface },
	PmenuExtraSel = { fg = colors.text, bg = colors.selection, bold = true },
	PmenuSbar = { bg = colors.raised },
	PmenuThumb = { bg = colors.border },
	SpellBad = { undercurl = true, sp = colors.error },
	SpellCap = { undercurl = true, sp = colors.warning },
	SpellLocal = { undercurl = true, sp = colors.cyan },
	SpellRare = { undercurl = true, sp = colors.violet },

	Comment = { fg = colors.muted },
	Constant = { fg = colors.peach },
	String = { fg = colors.green },
	Character = { fg = colors.green },
	Number = { fg = colors.peach },
	Boolean = { fg = colors.peach },
	Float = { fg = colors.peach },
	Identifier = { fg = colors.text },
	Function = { fg = colors.blue },
	Statement = { fg = colors.violet },
	Conditional = { fg = colors.violet },
	Repeat = { fg = colors.violet },
	Label = { fg = colors.violet },
	Operator = { fg = colors.cyan },
	Keyword = { fg = colors.violet },
	Exception = { fg = colors.violet },
	PreProc = { fg = colors.violet },
	Include = { fg = colors.violet },
	Define = { fg = colors.violet },
	Macro = { fg = colors.violet },
	PreCondit = { fg = colors.violet },
	Type = { fg = colors.ice },
	StorageClass = { fg = colors.violet },
	Structure = { fg = colors.ice },
	Typedef = { fg = colors.ice },
	Special = { fg = colors.distant_blue },
	SpecialChar = { fg = colors.violet },
	Tag = { fg = colors.blue },
	Delimiter = { fg = colors.muted },
	SpecialComment = { fg = colors.muted },
	Debug = { fg = colors.distant_blue },
	Underlined = { fg = colors.blue, underline = true },
	Ignore = { fg = colors.muted },
	Error = { fg = colors.error },
	Todo = { fg = colors.base, bg = colors.warning, bold = true },

	["@comment"] = { link = "Comment" },
	["@comment.documentation"] = { fg = colors.muted },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { fg = colors.distant_blue },
	["@constant.macro"] = { fg = colors.peach },
	["@string"] = { link = "String" },
	["@string.documentation"] = { fg = colors.green },
	["@string.escape"] = { fg = colors.violet },
	["@string.regexp"] = { fg = colors.green },
	["@character"] = { link = "Character" },
	["@number"] = { link = "Number" },
	["@number.float"] = { link = "Float" },
	["@boolean"] = { link = "Boolean" },
	["@variable"] = { fg = colors.text },
	["@variable.builtin"] = { fg = colors.distant_blue },
	["@variable.parameter"] = { fg = colors.secondary },
	["@variable.parameter.builtin"] = { fg = colors.distant_blue },
	["@variable.member"] = { fg = colors.cyan },
	["@property"] = { fg = colors.cyan },
	["@module"] = { fg = colors.ice },
	["@module.builtin"] = { fg = colors.distant_blue },
	["@label"] = { fg = colors.violet },
	["@function"] = { link = "Function" },
	["@function.builtin"] = { fg = colors.distant_blue },
	["@function.call"] = { fg = colors.blue },
	["@function.macro"] = { fg = colors.violet },
	["@function.method"] = { fg = colors.blue },
	["@function.method.call"] = { fg = colors.blue },
	["@constructor"] = { fg = colors.blue },
	["@operator"] = { link = "Operator" },
	["@keyword"] = { link = "Keyword" },
	["@keyword.function"] = { fg = colors.violet },
	["@keyword.operator"] = { fg = colors.violet },
	["@keyword.import"] = { fg = colors.violet },
	["@keyword.return"] = { fg = colors.violet },
	["@keyword.conditional"] = { fg = colors.violet },
	["@keyword.repeat"] = { fg = colors.violet },
	["@keyword.exception"] = { fg = colors.violet },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { fg = colors.distant_blue },
	["@type.definition"] = { fg = colors.ice },
	["@attribute"] = { fg = colors.peach },
	["@punctuation.delimiter"] = { fg = colors.muted },
	["@punctuation.bracket"] = { fg = colors.muted },
	["@punctuation.special"] = { fg = colors.violet },
	["@tag"] = { fg = colors.blue },
	["@tag.attribute"] = { fg = colors.cyan },
	["@tag.delimiter"] = { fg = colors.muted },

	["@markup.heading.1"] = { fg = colors.ice, bold = true },
	["@markup.heading.2"] = { fg = colors.blue, bold = true },
	["@markup.heading.3"] = { fg = colors.cyan, bold = true },
	["@markup.heading.4"] = { fg = colors.distant_blue, bold = true },
	["@markup.heading.5"] = { fg = colors.secondary, bold = true },
	["@markup.heading.6"] = { fg = colors.muted, bold = true },
	["@markup.strong"] = { fg = colors.text, bold = true },
	["@markup.italic"] = { fg = colors.ice, italic = true },
	["@markup.strikethrough"] = { fg = colors.muted, strikethrough = true },
	["@markup.quote"] = { fg = colors.muted },
	["@markup.link"] = { fg = colors.blue },
	["@markup.link.label"] = { fg = colors.blue },
	["@markup.link.url"] = { fg = colors.ice, underline = true },
	["@markup.list"] = { fg = colors.blue },
	["@markup.raw"] = { fg = colors.green },
	["@markup.raw.block"] = { fg = colors.green },
	["@markup.math"] = { fg = colors.ice },

	Added = { fg = colors.green },
	Changed = { fg = colors.peach },
	Removed = { fg = colors.error },
	DiffAdd = { bg = "#162620" },
	DiffChange = { bg = colors.deep },
	DiffDelete = { bg = "#2B1C23" },
	DiffText = { bg = colors.selection },
	diffAdded = { fg = colors.green },
	diffRemoved = { fg = colors.error },
	diffChanged = { fg = colors.peach },
	diffFile = { fg = colors.blue },
	diffLine = { fg = colors.ice },
	diffIndexLine = { fg = colors.muted },

	DiagnosticError = { fg = colors.error },
	DiagnosticWarn = { fg = colors.warning },
	DiagnosticInfo = { fg = colors.cyan },
	DiagnosticHint = { fg = colors.distant_blue },
	DiagnosticOk = { fg = colors.green },
	DiagnosticVirtualTextError = { fg = colors.error, bg = "#2B1C23" },
	DiagnosticVirtualTextWarn = { fg = colors.warning, bg = colors.deep },
	DiagnosticVirtualTextInfo = { fg = colors.cyan, bg = colors.deep },
	DiagnosticVirtualTextHint = { fg = colors.distant_blue, bg = colors.deep },
	DiagnosticVirtualTextOk = { fg = colors.green, bg = "#162620" },
	DiagnosticSignError = { link = "DiagnosticError" },
	DiagnosticSignWarn = { link = "DiagnosticWarn" },
	DiagnosticSignInfo = { link = "DiagnosticInfo" },
	DiagnosticSignHint = { link = "DiagnosticHint" },
	DiagnosticSignOk = { link = "DiagnosticOk" },
	DiagnosticFloatingError = { link = "DiagnosticError" },
	DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
	DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
	DiagnosticFloatingHint = { link = "DiagnosticHint" },
	DiagnosticFloatingOk = { link = "DiagnosticOk" },
	DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
	DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warning },
	DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
	DiagnosticUnderlineHint = { undercurl = true, sp = colors.distant_blue },
	DiagnosticUnderlineOk = { undercurl = true, sp = colors.green },
	DiagnosticUnnecessary = { fg = colors.muted },
	DiagnosticDeprecated = { fg = colors.muted, strikethrough = true },
	LspReferenceText = { bg = colors.raised },
	LspReferenceRead = { bg = colors.raised },
	LspReferenceWrite = { bg = colors.selection },
	LspReferenceTarget = { bg = colors.selection },
	LspSignatureActiveParameter = { fg = colors.ice, bold = true },
	LspInlayHint = { fg = colors.muted, bg = colors.deep },
	LspCodeLens = { fg = colors.muted },
	LspCodeLensSeparator = { fg = colors.border },

	["@lsp.type.variable"] = { link = "@variable" },
	["@lsp.type.parameter"] = { link = "@variable.parameter" },
	["@lsp.type.property"] = { link = "@property" },
	["@lsp.type.function"] = { link = "@function" },
	["@lsp.type.method"] = { link = "@function.method" },
	["@lsp.type.class"] = { link = "@type" },
	["@lsp.type.interface"] = { link = "@type" },
	["@lsp.type.struct"] = { link = "@type" },
	["@lsp.type.enum"] = { link = "@type" },
	["@lsp.type.typeParameter"] = { link = "@type" },
	["@lsp.type.enumMember"] = { link = "@constant" },
	["@lsp.type.keyword"] = { link = "@keyword" },
	["@lsp.type.operator"] = { link = "@operator" },
	["@lsp.typemod.variable.defaultLibrary"] = { fg = colors.distant_blue },
	["@lsp.typemod.function.defaultLibrary"] = { fg = colors.distant_blue },
	["@lsp.typemod.type.defaultLibrary"] = { fg = colors.distant_blue },
	["@lsp.type.field.cs"] = { link = "@variable.member" },
	["@lsp.type.constant.cs"] = { link = "@constant" },
	["@lsp.type.extensionMethod.cs"] = { link = "@function.method" },
	["@lsp.type.recordClass.cs"] = { link = "@type" },
	["@lsp.type.recordStruct.cs"] = { link = "@type" },
	["@lsp.type.delegate.cs"] = { link = "@type" },
	["@lsp.type.module.cs"] = { link = "@module" },
	["@lsp.type.controlKeyword.cs"] = { link = "@keyword" },
	["@lsp.type.operatorOverloaded.cs"] = { link = "@operator" },
	["@lsp.type.label.cs"] = { link = "@label" },

	RenderMarkdownH1 = { fg = colors.ice, bold = true },
	RenderMarkdownH2 = { fg = colors.blue, bold = true },
	RenderMarkdownH3 = { fg = colors.cyan, bold = true },
	RenderMarkdownH4 = { fg = colors.distant_blue, bold = true },
	RenderMarkdownH5 = { fg = colors.secondary, bold = true },
	RenderMarkdownH6 = { fg = colors.muted, bold = true },
	RenderMarkdownH1Bg = { fg = colors.ice },
	RenderMarkdownH2Bg = { fg = colors.blue },
	RenderMarkdownH3Bg = { fg = colors.cyan },
	RenderMarkdownH4Bg = { fg = colors.distant_blue },
	RenderMarkdownH5Bg = { fg = colors.secondary },
	RenderMarkdownH6Bg = { fg = colors.muted },
	RenderMarkdownCode = { fg = colors.green },
	RenderMarkdownCodeInfo = { fg = colors.ice },
	RenderMarkdownCodeBorder = { fg = colors.border },
	RenderMarkdownCodeFallback = { fg = colors.green },
	RenderMarkdownCodeInline = { fg = colors.green },
	RenderMarkdownQuote = { fg = colors.muted },
	RenderMarkdownBullet = { fg = colors.blue },
	RenderMarkdownDash = { fg = colors.border },
	RenderMarkdownSign = { fg = colors.blue },
	RenderMarkdownMath = { fg = colors.ice },
	RenderMarkdownLink = { fg = colors.blue },
	RenderMarkdownLinkTitle = { fg = colors.blue },
	RenderMarkdownWikiLink = { fg = colors.ice },
	RenderMarkdownUnchecked = { fg = colors.muted, bold = true },
	RenderMarkdownChecked = { fg = colors.base, bg = colors.green, bold = true },
	RenderMarkdownTodo = { fg = colors.warning, bold = true },
	RenderMarkdownTableHead = { fg = colors.ice },
	RenderMarkdownTableRow = { fg = colors.border },
	RenderMarkdownSuccess = { fg = colors.green },
	RenderMarkdownInfo = { fg = colors.cyan },
	RenderMarkdownHint = { fg = colors.distant_blue },
	RenderMarkdownWarn = { fg = colors.warning },
	RenderMarkdownError = { fg = colors.error },

	TelescopeNormal = { fg = colors.muted, bg = colors.surface },
	TelescopeBorder = { fg = colors.border, bg = colors.surface },
	TelescopeTitle = { fg = colors.ice, bg = colors.surface, bold = true },
	TelescopeSelection = { fg = colors.text, bg = colors.selection, bold = true },
	TelescopeSelectionCaret = { fg = colors.text, bg = colors.selection },
	TelescopeMultiSelection = { fg = colors.ice, bg = colors.selection },
	TelescopeMatching = { fg = colors.ice, bold = true },
	TelescopePromptPrefix = { fg = colors.blue },
	TelescopePromptCounter = { fg = colors.muted },
	TelescopePreviewLine = { fg = colors.text, bg = colors.selection },
	TelescopePreviewMatch = { fg = colors.ice, bg = colors.selection, bold = true },
	TelescopeResultsMethod = { fg = colors.blue },
	TelescopeResultsStruct = { fg = colors.ice },

	BlinkCmpMenu = { fg = colors.muted, bg = colors.surface },
	BlinkCmpMenuBorder = { fg = colors.border, bg = colors.surface },
	BlinkCmpMenuSelection = { fg = colors.text, bg = colors.selection, bold = true },
	BlinkCmpLabel = { fg = colors.secondary },
	BlinkCmpLabelMatch = { fg = colors.ice, bold = true },
	BlinkCmpLabelDeprecated = { fg = colors.muted, strikethrough = true },
	BlinkCmpLabelDetail = { fg = colors.muted },
	BlinkCmpLabelDescription = { fg = colors.muted },
	BlinkCmpSource = { fg = colors.muted },
	BlinkCmpKind = { fg = colors.cyan },
	BlinkCmpGhostText = { fg = colors.muted },
	BlinkCmpDoc = { fg = colors.secondary, bg = colors.surface },
	BlinkCmpDocBorder = { fg = colors.border, bg = colors.surface },
	BlinkCmpDocSeparator = { fg = colors.border },
	BlinkCmpDocCursorLine = { bg = colors.selection },
	BlinkCmpSignatureHelp = { fg = colors.secondary, bg = colors.surface },
	BlinkCmpSignatureHelpBorder = { fg = colors.border, bg = colors.surface },
	BlinkCmpSignatureHelpActiveParameter = { fg = colors.ice, bold = true },
	BlinkCmpKindFunction = { fg = colors.blue },
	BlinkCmpKindMethod = { fg = colors.blue },
	BlinkCmpKindVariable = { fg = colors.text },
	BlinkCmpKindField = { fg = colors.cyan },
	BlinkCmpKindProperty = { fg = colors.cyan },
	BlinkCmpKindClass = { fg = colors.ice },
	BlinkCmpKindInterface = { fg = colors.ice },
	BlinkCmpKindStruct = { fg = colors.ice },
	BlinkCmpKindTypeParameter = { fg = colors.ice },
	BlinkCmpKindConstant = { fg = colors.peach },
	BlinkCmpKindEnum = { fg = colors.ice },
	BlinkCmpKindEnumMember = { fg = colors.peach },
	BlinkCmpKindKeyword = { fg = colors.violet },
	BlinkCmpKindOperator = { fg = colors.cyan },
	BlinkCmpKindSnippet = { fg = colors.distant_blue },
	BlinkCmpKindFile = { fg = colors.secondary },
	BlinkCmpKindFolder = { fg = colors.blue },

	HarpoonNormal = { fg = colors.muted, bg = colors.surface },
	HarpoonSelection = { fg = colors.text, bg = colors.selection, bold = true },
	HarpoonCurrentFile = { fg = colors.ice, bold = true },

	NeotestPassed = { fg = colors.green },
	NeotestFailed = { fg = colors.error },
	NeotestRunning = { fg = colors.warning },
	NeotestSkipped = { fg = colors.muted },
	NeotestTest = { fg = colors.text },
	NeotestNamespace = { fg = colors.violet },
	NeotestFocused = { fg = colors.ice, bold = true, underline = true },
	NeotestFile = { fg = colors.blue },
	NeotestDir = { fg = colors.blue },
	NeotestIndent = { fg = colors.border },
	NeotestExpandMarker = { fg = colors.border },
	NeotestAdapterName = { fg = colors.peach },
	NeotestWinSelect = { fg = colors.cyan, bold = true },
	NeotestMarked = { fg = colors.peach, bold = true },
	NeotestTarget = { fg = colors.error },
	NeotestUnknown = { fg = colors.text },
	NeotestWatching = { fg = colors.warning },

	NotificationInfo = { fg = colors.text, bg = colors.surface },
	NotificationWarning = { fg = colors.base, bg = colors.warning },
	NotificationError = { fg = colors.base, bg = colors.error },
	EchoNotificationInfo = { fg = colors.cyan },
	EchoNotificationWarning = { fg = colors.warning },
	EchoNotificationError = { fg = colors.error },
	dbui_connection_ok = { fg = colors.green },
	dbui_connection_error = { fg = colors.error },

	DapBreakpoint = { fg = colors.error },
	DapStopped = { fg = colors.green, bg = colors.selection },
	DapUINormal = { link = "Normal" },
	DapUIVariable = { fg = colors.text },
	DapUIScope = { fg = colors.violet },
	DapUIType = { fg = colors.ice },
	DapUIValue = { fg = colors.secondary },
	DapUIModifiedValue = { fg = colors.warning, bold = true },
	DapUIDecoration = { fg = colors.blue },
	DapUIThread = { fg = colors.green },
	DapUIStoppedThread = { fg = colors.warning },
	DapUIFrameName = { fg = colors.text },
	DapUICurrentFrameName = { fg = colors.ice, bold = true },
	DapUISource = { fg = colors.blue },
	DapUILineNumber = { fg = colors.muted },
	DapUIFloatNormal = { link = "NormalFloat" },
	DapUIFloatBorder = { link = "FloatBorder" },
	DapUIWatchesEmpty = { fg = colors.muted },
	DapUIWatchesValue = { fg = colors.green },
	DapUIWatchesError = { fg = colors.error },
	DapUIBreakpointsPath = { fg = colors.blue },
	DapUIBreakpointsInfo = { fg = colors.green },
	DapUIBreakpointsCurrentLine = { fg = colors.ice, bold = true },
	DapUIBreakpointsLine = { fg = colors.muted },
	DapUIBreakpointsDisabledLine = { fg = colors.border },
	NvimDapVirtualText = { fg = colors.muted },
	NvimDapVirtualTextChanged = { fg = colors.warning },
	NvimDapVirtualTextError = { fg = colors.error },
	NvimDapVirtualTextInfo = { fg = colors.cyan },

	FlashBackdrop = { fg = colors.muted },
	FlashMatch = { fg = colors.ice, bg = colors.selection },
	FlashCurrent = { fg = "#ff0000", bold = true },
	FlashLabel = { fg = colors.base, bg = colors.ice, bold = true },
	FlashPrompt = { fg = colors.secondary },
	FlashPromptIcon = { fg = colors.blue },
	FlashCursor = { fg = colors.base, bg = colors.ice },
	MultiCursorCursor = { fg = colors.base, bg = colors.blue },
	MultiCursorVisual = { link = "Visual" },
	MultiCursorSign = { fg = colors.blue },
	MultiCursorMatchPreview = { fg = colors.ice, bg = colors.selection },
	MultiCursorDisabledCursor = { fg = colors.muted, bg = colors.raised },
	MultiCursorDisabledVisual = { fg = colors.muted, bg = colors.deep },
	MultiCursorDisabledSign = { fg = colors.border },
}

return {
	colors = colors,
	groups = groups,
	highlights = {
		dap_breakpoint = groups.DapBreakpoint,
		dap_stopped = groups.DapStopped,
		flash_current = groups.FlashCurrent,
		multicursor = groups.MultiCursorCursor,
	},
	lualine = {
		normal = {
			a = { fg = colors.base, bg = colors.blue, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		insert = {
			a = { fg = colors.base, bg = colors.green, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		visual = {
			a = { fg = colors.base, bg = colors.violet, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		replace = {
			a = { fg = colors.base, bg = colors.error, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		command = {
			a = { fg = colors.base, bg = colors.warning, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		terminal = {
			a = { fg = colors.base, bg = colors.cyan, gui = "bold" },
			b = { fg = colors.secondary, bg = colors.raised },
			c = { fg = colors.secondary, bg = colors.deep },
		},
		inactive = {
			a = { fg = colors.muted, bg = colors.deep },
			b = { fg = colors.muted, bg = colors.deep },
			c = { fg = colors.muted, bg = colors.deep },
		},
	},
	plugin = {
		{
			name = "biei",
			dir = vim.fn.stdpath("config"),
			lazy = false,
			priority = 1000,
			config = function()
				vim.cmd.colorscheme("biei")
			end,
		},
	},
}
