gui:
  sidePanelWidth: 0.4
  expandFocusedSidePanel: true
  wrapMainPanel: false
  showBottomLine: false
  returnImmediately: true
  theme:
    activeBorderColor:
      - '#f2cdcd'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
