gui:
  sidePanelWidth: 0.4
  expandFocusedSidePanel: true
  wrapMainPanel: false
  showBottomLine: false
  returnImmediately: true
  theme:
    activeBorderColor:
      - '#a9cce8'
      - bold
    inactiveBorderColor:
      - '#3a4652'
    optionsTextColor:
      - '#7fb5e5'
    selectedLineBgColor:
      - '#223246'
