git:
  autoFetch: false
  diffContextSize: 0
  diffRenderers:
    - colorArg: always
      command: delta --config "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/theme/delta.gitconfig" --features="dotfiles"
    - colorArg: always
      command: delta --config "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/theme/delta.gitconfig" --features="dotfiles" -s
promptToReturnFromSubprocess: false
gui:
  sidePanelWidth: 0.4
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  wrapLinesInStagingView: false
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  showNumstatInFilesView: true
  showPanelJumps: true
  showRandomTip: false
  theme:
    activeBorderColor:
      - '#f2cdcd'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f2cdcd'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
