$font = MesloLGS Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(11111bff)
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    inner_color = rgba(1e1e2eff)
    outer_color = rgba(89b4faff)
    font_color = rgba(cdd6f4ff)
    fail_color = rgba(f38ba8ff)
    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL
    fade_on_empty = false
    rounding = 12
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_family = $font
    font_size = 72
    color = rgba(cdd6f4ff)
    position = 0, 100
    halign = center
    valign = center
}
